version: '3.8'

services:
  backend:
    build:
      context: ./backend-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOSTNAME=backend-service
      - POD_IP=localhost
    volumes:
      - ./backend-service:/app
      - /app/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - HOSTNAME=frontend-service
      - POD_IP=localhost
      - BACKEND_SERVICE=http://backend:3000
    volumes:
      - ./frontend-service:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 
